// <auto-generated />
using System;
using CashVouchersManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CashVouchersManager.Infrastructure.Migrations
{
    [DbContext(typeof(CashVouchersDbContext))]
    partial class CashVouchersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CashVouchersManager.Domain.Entities.CashVoucher", b =>
                {
                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssuingSaleId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("IssuingStoreId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RedemptionSaleId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasIndex("Code")
                        .HasDatabaseName("IX_CashVouchers_Code");

                    b.ToTable("CashVouchers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
